### ISSUE TITLE
add support for arc.json and arc.yaml (instead of just .arc)

### ISSUE THREAD

**Issue by brianleroux** [arc-repos/arc-workflows#98]
Recently we got a little attention on hackernews and I was a bit dismayed that much of the conversation was focused on the `.arc` format. Rather than defend it as the *only* option I'd rather present it as the best option. And hopefully the conversation can move towards the more tangible benefits! I've found we barely spend any time in `.arc` even though it is an important communication vehicle for the intent of an application (vs a manifest of vendor infra and non-portable nomenclature).

I briefly revisited TOML but found the lack of anon/unnamed "tables" makes it unsuitable for how we're approaching config. 

Currently `.arc` is read only once in `arc-workflows/src/utill/init`; we should refactor it to look first for `.arc`, then `arc.yaml` and finally `arc.json`. If nothing is found it should error out. 

The following files will be equivalent:

A proper `.arc` file:

```.arc
# commenst oo ehh
@app
testapp

@domain
testapp.com

@aws
region us-west-2
profile personal

@static
staging testapp-bucket
production testapp-buckea-prod

@html
get /
post /login

@css
/index.css

@js
/js/index.js
/js/:mjs

@text
/robots.txt
/humans.txt

@json
get /api/notes
put /api/notes/:noteID
post /api/notes
delete /api/notes/:noteID
patch /api/notes/:noteID

@xml
get /index.rss

@events:
send-welcome-sms

@tables
notes:
  authorID *String
  noteID **String

authors
  authorID *String

@indexes
authors
  phone *String

@scheduled
daily-report rate(1 day)

@slack:
statsbot
```

An `arc.yaml` file (which isn't bad really…but does get a bit hairy when you arrive at tables):

```yaml
---
# commenst oo ehh
app: testapp
description: Example arc-to-json
domain: testapp.com
aws:
  region: us-west-2
  profile: personal
static:
  staging: testapp-bucket
  production: testapp-buckea-prod
html:
- get: "/"
- post: "/login"
css:
- "/index.css"
js:
- "/js/index.js"
- "/js/:mjs"
text:
- "/robots.txt"
- "/humans.txt"
json:
- get: "/api/notes"
- put: "/api/notes/:noteID"
- post: "/api/notes"
- delete: "/api/notes/:noteID"
- patch: "/api/notes/:noteID"
xml:
- get: index.rss
events:
- send-welcome-sms
tables:
- notes:
    authorID: "*String"
    noteID: "**String"
- authors:
    authorID: "*String"
indexes:
- authors:
    phone: "*String"
scheduled:
  daily-report: rate(1 day)
slack:
- statsbot
```

…and finally the most verbose, rigid and of course lacking comments `arc.json`:

```json
{
  "app": "testapp",
  "description": "Example arc-to-json",
  "domain": "testapp.com",
  "aws": {
    "region": "us-west-2",
    "profile": "personal"
  },
  "static": {
    "staging": "testapp-bucket",
    "production": "testapp-buckea-prod"
  },
  "html": [
    {
      "get": "/"
    },
    {
      "post": "/login"
    }
  ],
  "css": [
    "/index.css"
  ],
  "js": [
    "/js/index.js",
    "/js/:mjs"
  ],
  "text": [
    "/robots.txt",
    "/humans.txt"
  ],
  "json": [
    {
      "get": "/api/notes"
    },
    {
      "put": "/api/notes/:noteID"
    },
    {
      "post": "/api/notes"
    },
    {
      "delete": "/api/notes/:noteID"
    },
    {
      "patch": "/api/notes/:noteID"
    }
  ],
  "xml": [
    {
      "get": "index.rss"
    }
  ],
  "events": [
    "send-welcome-sms"
  ],
  "tables": [
    {
      "notes": {
        "authorID": "*String",
        "noteID": "**String"
      }
    },
    {
      "authors": {
        "authorID": "*String"
      }
    }
  ],
  "indexes": [
    {
      "authors": {
        "phone": "*String"
      }
    }
  ],
  "scheduled": {
    "daily-report": "rate(1 day)"
  },
  "slack": [
    "statsbot"
  ]
}
```

**Comment by brianleroux** [comment]
side note: h/t to @csantanapr for giving me the same feedback roughly a year ago! finally we get around to it. ;P

**Comment by gauntface** [comment]
I'm just going to put json5 on your radar as it would give you comment support.

I believe it's the format used in VSCode's settings editor.

**Comment by QuinnyPig** [comment]
If it's not a major undertaking, absolutely do it. "Meet people where they are."

This may also open the door for interoperability with SAM, Serverless Framework, etc...

**Comment by brianleroux** [comment]
published in `@architect/workflows@3.4.0`; just need to add docs! here's the tester file I was using 

```yaml
---
app: testapp-ragalkasklsadlksdlklkds
aws:
  region: us-east-1
  profile: personal
events:
- one
- two
html:
- get: "/"
json:
- get: "/api"
text:
- "/hi"
queues:
- test-q

```
